name: Simple Workflow

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://801d69da6218.ngrok-free.app
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/foo foo
            
      - name: Step following 'Import Secrets'
        run: |
          touch secrets.json
          echo '${{ toJson(steps.import-secrets.outputs) }}' >> secrets.json
          cat secrets.json
          
      - name: Upload simple artifact (Do not do it, just for sample)
        uses: actions/upload-artifact@v4
        with:
          name: secrets
          path: secrets.json
